// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class MagicDoesThings
{
    public static class Keyword
    {
        private static FormLink<IKeywordGetter> Construct(uint id) => new FormLink<IKeywordGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IKeywordGetter> _MDT_StaffLensKeyword => Construct(0x804);
        public static FormLink<IKeywordGetter> _MDT_StaffEnchKeyword => Construct(0x970);
        public static FormLink<IKeywordGetter> _MDT_FireStaffKeyword => Construct(0x97c);
        public static FormLink<IKeywordGetter> _MDT_FrostStaffKeyword => Construct(0x97d);
        public static FormLink<IKeywordGetter> _MDT_ShockStaffKeyword => Construct(0x97e);
        public static FormLink<IKeywordGetter> _MDT_SoulTrapStaffKeyword => Construct(0x97f);
        public static FormLink<IKeywordGetter> _MDT_ReanimateStaffKeyword => Construct(0x980);
        public static FormLink<IKeywordGetter> _MDT_BanishStaffKeyword => Construct(0x981);
        public static FormLink<IKeywordGetter> _MDT_PoisonStaffKeyword => Construct(0x984);
        public static FormLink<IKeywordGetter> _MDT_ConfidenceStaffKeyword => Construct(0x985);
        public static FormLink<IKeywordGetter> _MDT_AggressionStaffKeyword => Construct(0x986);
        public static FormLink<IKeywordGetter> _MDT_SunStaffKeyword => Construct(0x987);
        public static FormLink<IKeywordGetter> _MDT_TurnStaffKeyword => Construct(0x988);
        public static FormLink<IKeywordGetter> _MDT_CommandStaffKeyword => Construct(0x989);
        public static FormLink<IKeywordGetter> _MDT_LightStaffKeyword => Construct(0x98a);
        public static FormLink<IKeywordGetter> _MDT_ParalysisStaffKeyword => Construct(0x98b);
        public static FormLink<IKeywordGetter> _MDT_AshStaffKeyword => Construct(0x99c);
        public static FormLink<IKeywordGetter> _MDT_BloodStaffKeyword => Construct(0x99d);
        public static FormLink<IKeywordGetter> _MDT_MagnusStaffKeyword => Construct(0x9a2);
        public static FormLink<IKeywordGetter> _MDT_WabbajackKeyword => Construct(0x9a6);
        public static FormLink<IKeywordGetter> _MDT_ScrollKeyword => Construct(0x9b6);
        public static FormLink<IKeywordGetter> _MDT_DefaultDestructionStaffKeyword => Construct(0xa57);
        public static FormLink<IKeywordGetter> _MDT_DefaultAlterationStaffKeyword => Construct(0xa87);
    }
}
