// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class MagicDoesThings
{
    public readonly static ModKey ModKey = ModKey.FromNameAndExtension("MagicDoesThings.esp");
}
