// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class MagicDoesThings
{
    public static class Perk
    {
        private static FormLink<IPerkGetter> Construct(uint id) => new FormLink<IPerkGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPerkGetter> _MDT_MasterPerk => Construct(0x805);
        public static FormLink<IPerkGetter> _MDT_AIVanillaStavesPerk => Construct(0x815);
        public static FormLink<IPerkGetter> _MDT_StaffOfMagnusPerk => Construct(0x8c9);
        public static FormLink<IPerkGetter> _MDT_WabbajackPerk => Construct(0x8d1);
        public static FormLink<IPerkGetter> _MDT_SkullOfCorruptionPerk => Construct(0x8d9);
        public static FormLink<IPerkGetter> _MDT_StaffOfGauldursonPerk => Construct(0x91a);
        public static FormLink<IPerkGetter> _MDT_ParalysisStaffPerk => Construct(0x946);
        public static FormLink<IPerkGetter> _MDT_BanishDaedraStaffPerk => Construct(0x947);
        public static FormLink<IPerkGetter> _MDT_FrostAtronachStaffPerk => Construct(0x948);
        public static FormLink<IPerkGetter> _MDT_RevenantStaffPerk => Construct(0x949);
        public static FormLink<IPerkGetter> _MDT_CommandDaedraStaffPerk => Construct(0x94a);
        public static FormLink<IPerkGetter> _MDT_DreadZombieStaffPerk => Construct(0x94b);
        public static FormLink<IPerkGetter> _MDT_StormAtronachStaffPerk => Construct(0x94c);
        public static FormLink<IPerkGetter> _MDT_ExpelDaedraStaffPerk => Construct(0x94d);
        public static FormLink<IPerkGetter> _MDT_FireballStaffPerk => Construct(0x94e);
        public static FormLink<IPerkGetter> _MDT_IceStormStaffPerk => Construct(0x94f);
        public static FormLink<IPerkGetter> _MDT_FrostbiteStaffPerk => Construct(0x950);
        public static FormLink<IPerkGetter> _MDT_ChainLightningStaffPerk => Construct(0x951);
        public static FormLink<IPerkGetter> _MDT_WallOfFlamesStaffPerk => Construct(0x952);
        public static FormLink<IPerkGetter> _MDT_WallOfFrostStaffPerk => Construct(0x953);
        public static FormLink<IPerkGetter> _MDT_StormWallStaffPerk => Construct(0x954);
        public static FormLink<IPerkGetter> _MDT_RallyStaffPerk => Construct(0x955);
        public static FormLink<IPerkGetter> _MDT_FrenzyStaffPerk => Construct(0x956);
        public static FormLink<IPerkGetter> _MDT_TandilStaffPerk => Construct(0x957);
        public static FormLink<IPerkGetter> _MDT_RoutStaffPerk => Construct(0x958);
        public static FormLink<IPerkGetter> _MDT_MendingStaffPerk => Construct(0x959);
        public static FormLink<IPerkGetter> _MDT_RepelLesserUndeadStaffPerk => Construct(0x95a);
        public static FormLink<IPerkGetter> _MDT_TurnGreaterUndeadStaffPerk => Construct(0x95b);
        public static FormLink<IPerkGetter> _MDT_TurnUndeadStaffPerk => Construct(0x95c);
        public static FormLink<IPerkGetter> _MDT_RepelUndeadStaffPerk => Construct(0x95d);
        public static FormLink<IPerkGetter> _MDT_FireboltStaffPerk => Construct(0x95e);
        public static FormLink<IPerkGetter> _MDT_IceSpikeStaffPerk => Construct(0x95f);
        public static FormLink<IPerkGetter> _MDT_LightningBoltStaffPerk => Construct(0x960);
        public static FormLink<IPerkGetter> _MDT_FlamesStaffPerk => Construct(0x961);
        public static FormLink<IPerkGetter> _MDT_SparksStaffPerk => Construct(0x962);
        public static FormLink<IPerkGetter> _MDT_RaiseZombieStaffPerk => Construct(0x963);
        public static FormLink<IPerkGetter> _MDT_FamiliarStaffPerk => Construct(0x964);
        public static FormLink<IPerkGetter> _MDT_CourageStaffPerk => Construct(0x965);
        public static FormLink<IPerkGetter> _MDT_FuryStaffPerk => Construct(0x966);
        public static FormLink<IPerkGetter> _MDT_ReanimateCorpseStaffPerk => Construct(0x967);
        public static FormLink<IPerkGetter> _MDT_FearStaffPerk => Construct(0x968);
        public static FormLink<IPerkGetter> _MDT_CalmStaffPerk => Construct(0x969);
        public static FormLink<IPerkGetter> _MDT_RecoveryStaffPerk => Construct(0x96a);
        public static FormLink<IPerkGetter> _MDT_TurnLesserUndeadStaffPerk => Construct(0x96b);
        public static FormLink<IPerkGetter> _MDT_IncinerationStaffPerk => Construct(0x96c);
        public static FormLink<IPerkGetter> _MDT_IcySpearStaffPerk => Construct(0x96d);
        public static FormLink<IPerkGetter> _MDT_MiraaksStaffPerk => Construct(0x96e);
        public static FormLink<IPerkGetter> _MDT_FlameAtronachStaffPerk => Construct(0x96f);
        public static FormLink<IPerkGetter> _MDT_AetherialStaffPerk => Construct(0x997);
        public static FormLink<IPerkGetter> _MDT_FireboltScrollPerk => Construct(0x9b4);
        public static FormLink<IPerkGetter> _MDT_MassParalysisScrollPerk => Construct(0x9bf);
        public static FormLink<IPerkGetter> _MDT_IceSpikeScrollPerk => Construct(0x9c2);
        public static FormLink<IPerkGetter> _MDT_LightningBoltScrollPerk => Construct(0x9c5);
        public static FormLink<IPerkGetter> _MDT_CandlelightScrollPerk => Construct(0x9c9);
        public static FormLink<IPerkGetter> _MDT_OakfleshScrollPerk => Construct(0x9cc);
        public static FormLink<IPerkGetter> _MDT_RaiseZombieScrollPerk => Construct(0x9cf);
        public static FormLink<IPerkGetter> _MDT_ConjureFamiliarScrollPerk => Construct(0x9d2);
        public static FormLink<IPerkGetter> _MDT_CourageScrollPerk => Construct(0x9d5);
        public static FormLink<IPerkGetter> _MDT_FuryScrollPerk => Construct(0x9d8);
        public static FormLink<IPerkGetter> _MDT_MagelightScrollPerk => Construct(0x9db);
        public static FormLink<IPerkGetter> _MDT_StonefleshScrollPerk => Construct(0x9de);
        public static FormLink<IPerkGetter> _MDT_ReanimateCorpseScrollPerk => Construct(0x9e1);
        public static FormLink<IPerkGetter> _MDT_ConjureFlameAtronachScrollPerk => Construct(0x9e4);
        public static FormLink<IPerkGetter> _MDT_SoulTrapScrollPerk => Construct(0x9e7);
        public static FormLink<IPerkGetter> _MDT_FireRuneScrollPerk => Construct(0x9ea);
        public static FormLink<IPerkGetter> _MDT_FrostRuneScrollPerk => Construct(0x9ed);
        public static FormLink<IPerkGetter> _MDT_ShockRuneScrollPerk => Construct(0x9f0);
        public static FormLink<IPerkGetter> _MDT_MuffleScrollPerk => Construct(0x9f3);
        public static FormLink<IPerkGetter> _MDT_CalmScrollPerk => Construct(0x9f6);
        public static FormLink<IPerkGetter> _MDT_FearScrollPerk => Construct(0x9f9);
        public static FormLink<IPerkGetter> _MDT_FastHealingScrollPerk => Construct(0x9fc);
        public static FormLink<IPerkGetter> _MDT_TurnUndeadScrollPerk => Construct(0x9ff);
        public static FormLink<IPerkGetter> _MDT_SoulTrapStaffPerk => Construct(0xa00);
        public static FormLink<IPerkGetter> _MDT_TemplateDestIlluRestoStaffPerk => Construct(0xa01);
        public static FormLink<IPerkGetter> _MDT_TemplateConjuSummonReanimateStaffPerk => Construct(0xa02);
        public static FormLink<IPerkGetter> _MDT_TemplateAlteConjuNonSummonOrCommandStaffPerk => Construct(0xa03);
        public static FormLink<IPerkGetter> _MDT_TemplateConjuCommandStaffPerk => Construct(0xa43);
    }
}
